export const Fields = [
  {
    data: "#collapseOne",
    id: "collapseOne",
    header: "headerOne",
    optgroup: true,
    title: "Business, management and Entrepreneurship",
    value: [
      "Human Resource",
      "Marketing Sales",
      "Finance",
      "Operations",
      "Entrepreneurship",
      "Hotel Managment",
    ],
  },
  {
    data: "#collapseTwo",
    id: "collapseTwo",
    header: "headerTwo",
    optgroup: true,
    title: "Engineering",
    value: [
      "Information Technology Engineering",
      "Electronics and communication Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Civil Engineering",
      "Electrical And Instrumnentation Engineering",
      "AeroSpace Engineering",
      "BioTechnology",
    ],
  },
  {
    data: "#collapseThree",
    id: "collapseThree",
    header: "headerThree",
    optgroup: true,
    title: "Humanities and Social Science",
    value: [
      "Journalism, media Studies",
      "Economics",
      "Psychology",
      "Sociology",
      "Political Science",
      "Religion",
      "The Arts",
      "Languages",
      "History",
      "Geography",
    ],
  },
  {
    data: "#collapseFour",
    id: "collapseFour",
    header: "headerFour",
    optgroup: true,
    title: "Law and Public Policy",
    value: [
      "Civil Law",
      "Criminal Law",
      "Corporate Law",
      "Cyber Law",
      "Intellectual Property Law",
    ],
  },
  {
    data: "#collapseFive",
    id: "collapseFive",
    header: "headerFive",
    optgroup: true,
    title: "Health and medicine",
    value: [
      "General Practice and Surgery",
      "Ayurvedic",
      "Homeopathy",
      "Veternarians",
      "Dentists",
      "Pdiatrics",
      "Obstetrics and Gynaecology",
      "Dermatology",
      "Ophthalmology",
    ],
  },
];

export const AdvancedFields = [
  {
    title: "Information Technology Engineering",
    skills: [
      "Web Developer",
      "App Developer",
      "Python Web Developer",
      "PHP Backend Developer",
      "FrontEnd Developer",
      "MERN Stack Developer",
      "MEAN Stack Develper",
      "Machine Learning",
      "Data Scientist",
      "Software Architect",
    ],
  },
  {
    title: "Education and Teaching",
    skills: [
      "Elementary",
      "High School",
      "Professor",
      "Painter",
      "Dancer",
      "Advanced",
      "Beginner",
      "Accounts",
      "Cashier",
    ],
  },
  { title: "Mechanical Engineering", skills: ["Mechanic", "Plumber"] },
  { title: "The Arts", skills: ["Painter", "Dancer"] },
  { title: "Economics", skills: ["Accounts", "Cashier"] },
];
